name: Traceroute

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  verify_format:
    name: Verify code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update && sudo apt-get install -y clang-format
          ./verify-format.sh
  
  build:
    name: Build Traceroute
    runs-on: ubuntu-latest
    needs: [ verify_format ]
    steps:
      - uses: actions/checkout@v3
      - run: make
